// Error codes used across the platform

export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_OTP: 'AUTH_INVALID_OTP',
  AUTH_OTP_ATTEMPTS_EXCEEDED: 'AUTH_OTP_ATTEMPTS_EXCEEDED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_BIOMETRIC_REQUIRED: 'AUTH_BIOMETRIC_REQUIRED',
  AUTH_ACTION_TOKEN_EXPIRED: 'AUTH_ACTION_TOKEN_EXPIRED',
  AUTH_TOTP_INVALID: 'AUTH_TOTP_INVALID',
  AUTH_WEBAUTHN_FAILED: 'AUTH_WEBAUTHN_FAILED',

  // Orders
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_CANNOT_CANCEL: 'ORDER_CANNOT_CANCEL',

  // Payment
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  PAYMENT_DUPLICATE: 'PAYMENT_DUPLICATE',
  PAYMENT_METHOD_UNAVAILABLE: 'PAYMENT_METHOD_UNAVAILABLE',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',

  // Restaurant / Menu
  RESTAURANT_CLOSED: 'RESTAURANT_CLOSED',
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  MENU_ITEM_UNAVAILABLE: 'MENU_ITEM_UNAVAILABLE',
  RESTAURANT_PAUSED: 'RESTAURANT_PAUSED',

  // Cart
  CART_EMPTY: 'CART_EMPTY',
  CART_DIFFERENT_RESTAURANTS: 'CART_DIFFERENT_RESTAURANTS',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',

  // Promo
  PROMO_INVALID: 'PROMO_INVALID',
  PROMO_USAGE_LIMIT_REACHED: 'PROMO_USAGE_LIMIT_REACHED',
  PROMO_EXPIRED: 'PROMO_EXPIRED',
  PROMO_MIN_ORDER_NOT_MET: 'PROMO_MIN_ORDER_NOT_MET',

  // Driver
  DRIVER_NOT_AVAILABLE: 'DRIVER_NOT_AVAILABLE',
  DRIVER_OFFLINE: 'DRIVER_OFFLINE',
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  DRIVER_SUSPENDED: 'DRIVER_SUSPENDED',

  // Refund
  REFUND_AMOUNT_EXCEEDS_ORDER: 'REFUND_AMOUNT_EXCEEDS_ORDER',
  REFUND_WINDOW_CLOSED: 'REFUND_WINDOW_CLOSED',
  REFUND_ALREADY_PROCESSED: 'REFUND_ALREADY_PROCESSED',

  // Fraud
  FRAUD_DETECTED: 'FRAUD_DETECTED',
  FRAUD_REVIEW_REQUIRED: 'FRAUD_REVIEW_REQUIRED',

  // Permissions
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  DUAL_APPROVAL_REQUIRED: 'DUAL_APPROVAL_REQUIRED',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Audit
  AUDIT_CHAIN_BROKEN: 'AUDIT_CHAIN_BROKEN',
  AUDIT_VERIFICATION_FAILED: 'AUDIT_VERIFICATION_FAILED',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
